export const ROUTES = {
  storefront: {
    home: "/",
    cart: "/cart",
    account: "/account",
    accountProfile: "/account/profile",
    accountOrders: "/account/orders",
    accountOrder: (orderId: string) => `/account/orders/${orderId}`,
    accountWishlist: "/account/wishlist",
    accountNotifications: "/account/notifications",
    accountAddresses: "/account/addresses",
    accountSettings: "/account/settings",
    orders: "/orders",
    order: (orderId: string) => `/orders/${orderId}`,
    checkout: "/checkout",
    checkoutSuccess: "/checkout/success",
    checkoutFailed: "/checkout/failed",
    shop: "/shop",
    categories: "/categories",
    category: (slug: string) => `/categories/${slug}`,
    products: "/products",
    product: (slug: string) => `/products/${slug}`,
    collections: "/collections",
    contact: "/contact",
    faq: "/faq",
    policies: "/policies",
    shippingPolicy: "/policies/shipping",
    returnsPolicy: "/policies/returns",
    privacyPolicy: "/policies/privacy",
    designSystem: "/design-system",
    wishlist: "/account/wishlist",
  },
  admin: {
    dashboard: "/admin",
    analytics: "/admin/analytics",
    inventory: "/admin/inventory",
    shipping: "/admin/shipping",
    notifications: "/admin/notifications",
    products: "/admin/products",
    coupons: "/admin/coupons",
    orders: "/admin/orders",
    customers: "/admin/customers",
    categories: "/admin/categories",
    brands: "/admin/brands",
    banners: "/admin/banners",
  },
  auth: {
    signIn: "/sign-in",
    signUp: "/sign-up",
  },
} as const;

export const STOREFRONT_NAV_LINKS = [
  { label: "Home", href: ROUTES.storefront.home },
  { label: "Shop", href: ROUTES.storefront.shop },
  { label: "Categories", href: ROUTES.storefront.categories },
] as const;

export const ADMIN_NAV_LINKS = [
  { label: "Overview", href: ROUTES.admin.dashboard },
  { label: "Analytics", href: ROUTES.admin.analytics },
  { label: "Inventory", href: ROUTES.admin.inventory },
  { label: "Shipping", href: ROUTES.admin.shipping },
  { label: "Notifications", href: ROUTES.admin.notifications },
  { label: "Products", href: ROUTES.admin.products },
  { label: "Coupons", href: ROUTES.admin.coupons },
  { label: "Categories", href: ROUTES.admin.categories },
  { label: "Brands", href: ROUTES.admin.brands },
  { label: "Banners", href: ROUTES.admin.banners },
  { label: "Orders", href: ROUTES.admin.orders },
  { label: "Customers", href: ROUTES.admin.customers },
] as const;

export const ACCOUNT_NAV_LINKS = [
  { label: "Dashboard", href: ROUTES.storefront.account },
  { label: "Profile", href: ROUTES.storefront.accountProfile },
  { label: "Orders", href: ROUTES.storefront.accountOrders },
  { label: "Wishlist", href: ROUTES.storefront.accountWishlist },
  { label: "Notifications", href: ROUTES.storefront.accountNotifications },
  { label: "Addresses", href: ROUTES.storefront.accountAddresses },
  { label: "Settings", href: ROUTES.storefront.accountSettings },
] as const;
